### ISSUE TITLE
docker版无法上传图片

### ISSUE THREAD

**Issue by KITblue** [lomorage/lomo-docker#10]
![无标题](https://user-images.githubusercontent.com/68754977/154330631-d94ad9ae-f513-4b28-b541-e1d4fc28ad58.jpg)

手机app显示已经上传完成，但是web登录里面是空的，到目录里面看也是空的，web上传页面显示无法上传

**Comment by KITblue** [comment]
![image](https://user-images.githubusercontent.com/68754977/154331071-0391475d-906a-4350-9e92-32fda4c6964d.png)

**Comment by fuji246** [comment]
Which mobile APP are you using, Android or iOS? You can send feedback in the APP.

As for the uploading waring on web page, it's fixed and will release in next release. You can ignore the warning, the uploading should still work.

**Comment by KITblue** [comment]
Android&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jiantao ***@***.***&gt;; 
发送时间: 2022年2月17日(星期四) 凌晨2:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lomorage/lomo-docker] docker版无法上传图片 (Issue #10)





 
Which mobile APP are you using, Android or iOS? You can send feedback in the APP.
 
As for the uploading waring on web page, it's fixed and will release in next release. You can ignore the warning, the uploading should still work.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by KITblue** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Lau"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月17日(星期四) 凌晨2:31
***@***.******@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;回复： [lomorage/lomo-docker] docker版无法上传图片 (Issue #10)



 Android 




------------------ 原始邮件 ------------------
发件人: "Jiantao ***@***.***&gt;; 
发送时间: 2022年2月17日(星期四) 凌晨2:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [lomorage/lomo-docker] docker版无法上传图片 (Issue #10)





 
Which mobile APP are you using, Android or iOS? You can send feedback in the APP.
 
As for the uploading waring on web page, it's fixed and will release in next release. You can ignore the warning, the uploading should still work.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fuji246** [comment]
You can send feedback in email.
<img width="650" alt="image" src="https://user-images.githubusercontent.com/1052283/154336278-dcb7ed9a-65b0-47f9-bb86-6a029c209434.png">

**Comment by aisnote** [comment]
问题解决了吗

**Comment by fuji246** [comment]
LOMOD_DISABLE_MOUNT_MONITOR by default now.
