### ISSUE TITLE
docker安装完用户名密码是什么?

### ISSUE THREAD

**Issue by zgc999** [lomorage/lomo-docker#11]
docker安装后打开网页，需要账户密码

**Comment by fuji246** [comment]
需要手机APP创建用户。

**Comment by zgc999** [comment]
googlepaly安装好应用,提示创建用户失败（内部错误dir=0或者服务器没启动）.
docker安装的未使用vlan，能打开登录页面应该是已经安装成功了吧。

**Comment by aisnote** [comment]
从 手机app 设置页面 发个反馈 ，会有日志带上来，谢谢

**Comment by zgc999** [comment]
1645676565872,2022.02.24 12:22:45.872,ERROR,Lomorage-j,getSettingsFromExternalFolde: cnfFile not existed: /storage/emulated/0/Android/data/com.lomoware.lomorage/files/conf/local_dir_set.cnf
1645676566326,2022.02.24 12:22:46.326,INFO,Lomorage-r,androidId = 1026d33474a1b139
1645676566326,2022.02.24 12:22:46.326,INFO,Lomorage-r,mAndroidId = cf123d4fb6d2381f9a452b5877e315b79dcd1e43
1645676566365,2022.02.24 12:22:46.365,INFO,Lomorage-f,phone local today is: YYMM = 0224
1645676567047,2022.02.24 12:22:47.047,INFO,Lomorage-a,file size so small: 285, ignore
1645676567111,2022.02.24 12:22:47.111,WARN,Lomorage-a,format not support, file = /storage/emulated/0/com.tencent.mm/images/SMP_20201015_862659.gif
1645676567202,2022.02.24 12:22:47.202,ERROR,Lomorage-a,/storage/emulated/0/Pictures/1630639980609.jpg not a valid file
1645676567400,2022.02.24 12:22:47.400,ERROR,Lomorage-LomoSplashActivity$b,LomoSplashActivity>>loadLocalAssetsToDbAndStartMain timeCost = 1377
1645676567429,2022.02.24 12:22:47.429,DEBUG,Lomorage-MainActivity,main>>life>>onCreate
1645676567477,2022.02.24 12:22:47.477,ERROR,Lomorage-j,getSettingsFromExternalFolde: cnfFile not existed: /storage/emulated/0/Android/data/com.lomoware.lomorage/files/conf/local_dir_set.cnf
1645676567479,2022.02.24 12:22:47.479,INFO,Lomorage-p,isPrivacyShownBefore = true
1645676567482,2022.02.24 12:22:47.482,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676567483,2022.02.24 12:22:47.483,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676567483,2022.02.24 12:22:47.483,INFO,Lomorage-MainActivity,loading>> state = STATE_NEED_LOGIN, msg = 请登录服务器, hideProgress = false
1645676567483,2022.02.24 12:22:47.483,INFO,Lomorage-p,isPrivacyShownBefore = true
1645676567486,2022.02.24 12:22:47.486,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676567487,2022.02.24 12:22:47.487,INFO,Lomorage-MainActivity,loadAllPicturesOneByOne begin...  loadState = STATE_NEED_LOGIN
1645676567487,2022.02.24 12:22:47.487,INFO,Lomorage-a,BackupRepository init
1645676567488,2022.02.24 12:22:47.488,INFO,Lomorage-i,getAndroidVer, local version code = 35
1645676567489,2022.02.24 12:22:47.489,DEBUG,Lomorage-MainActivity,main>>life>>onResume true
1645676567577,2022.02.24 12:22:47.577,INFO,Lomorage-MainActivity,loading>> 正在分析本地相册...... 10 %
1645676567578,2022.02.24 12:22:47.578,INFO,Lomorage-MainActivity,loading>> state = STATE_COMPARING_REMOTE, msg = 对比服务器文件......, hideProgress = false
1645676567578,2022.02.24 12:22:47.578,INFO,Lomorage-a,DailyView>> setDailyViewDataSet, mSections.size = 283, mSectionsItems.size = 283
1645676567578,2022.02.24 12:22:47.578,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676567579,2022.02.24 12:22:47.579,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676567579,2022.02.24 12:22:47.579,INFO,Lomorage-MainActivity,loading>> state = STATE_NEED_LOGIN, msg = 请登录服务器, hideProgress = false
1645676567581,2022.02.24 12:22:47.581,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676567583,2022.02.24 12:22:47.583,DEBUG,Lomorage-MainActivity,fts.size = 0
1645676567593,2022.02.24 12:22:47.593,INFO,Lomorage-a,DailyView>> bind header, title = 周二: 2022年02月22日
1645676567601,2022.02.24 12:22:47.601,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676567601,2022.02.24 12:22:47.601,INFO,Lomorage-e,mItem = -2125318961, 2fe78c9fb90531067d6a70c4e5647ebb31f38221
1645676567610,2022.02.24 12:22:47.610,INFO,Lomorage-a,DailyView>> bind header, title = 周日: 2022年02月20日
1645676567612,2022.02.24 12:22:47.612,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676567612,2022.02.24 12:22:47.612,INFO,Lomorage-e,mItem = 1288628116, 14166006fb1f2ca6e3437d9c336ee338ce064ae4
1645676567619,2022.02.24 12:22:47.619,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676567619,2022.02.24 12:22:47.619,INFO,Lomorage-e,mItem = -1015628315, 367e4095fa8d6948867b999535e65d27459304ef
1645676567654,2022.02.24 12:22:47.654,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676567654,2022.02.24 12:22:47.654,INFO,Lomorage-e,mItem = -498661809, c51056bb25c2d6a644a742850259fb7911e2ffab
1645676567663,2022.02.24 12:22:47.663,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676567663,2022.02.24 12:22:47.663,INFO,Lomorage-e,mItem = -1826257779, e63d2beae4ddd0918abc8c5a9242f45c18314ac7
1645676567693,2022.02.24 12:22:47.693,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676567693,2022.02.24 12:22:47.693,INFO,Lomorage-e,mItem = 525668759, f2bd0c67ed669fb76f07e60933ad2b13f82dd5c9
1645676567704,2022.02.24 12:22:47.704,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676567704,2022.02.24 12:22:47.704,INFO,Lomorage-e,mItem = 1340409561, b67516b80e38ad3e61c287fb1411594e35b4cdad
1645676567745,2022.02.24 12:22:47.745,INFO,Lomorage-a,DailyView>> bind header, title = 周六: 2022年02月19日
1645676567747,2022.02.24 12:22:47.747,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676567748,2022.02.24 12:22:47.748,INFO,Lomorage-e,mItem = 1743999380, fa3bb82786eb10df30f68ee3bd6136a208645c3a
1645676569032,2022.02.24 12:22:49.032,INFO,Lomorage-t,updateLomod>> release.json = { <br>   "darwin": { <br>     "Version": "2022_02_17.13_35_34.0.052f008", <br>     "OS": "mac", <br>     "SHA256": "adf3739b23450ba50686562416baa01f826ce42fefe7de39d1b24067a0094ec9", <br>     "URL": "https://github.com/lomorage/LomoAgentOSX/releases/download/2022_02_17.13_35_34.0.052f008/LomoAgent.zip", <br>     "LomoUpgVer": "2019_12_09.23_41_36.0.b28a902", <br>     "LomoUpdateURL": "https://lomosw.lomorage.com/mac/LomoUpdate.zip" <br>   }, <br>   "windows": { <br>     "Version": "2021_11_07.09_55_01.0.099806b", <br>     "OS": "windows", <br>     "SHA256": "06791776EFB2434352CA2FFF9E987367E3B0DFB8D634DBAD5BF259AEBFD25FA9", <br>     "URL": "https://github.com/lomorage/LomoAgentWin/releases/download/2021_11_07.09_55_01.0.099806b/lomoagent-2021_11_07.09_55_01.0.099806b.zip", <br>     "LomoUpgVer": "2020_08_22.21_03_02.0.2f88662", <br>     "LomoUpdateURL": "https://lomosw.lomorage.com/windows/LomoUpdate.zip" <br>   }, <br>   "lomod": { <br>     "Commit": "b5abcb3" <br>   }, <br>   "android": { <br>     "VersionCode": "34", <br>     "ReleaseTime": "2021-12-16_21-59-03" <br>   } <br> } <br> 
1645676569033,2022.02.24 12:22:49.033,INFO,Lomorage-i$b$a,getAndroidVer>> remote version = 34
1645676570703,2022.02.24 12:22:50.703,DEBUG,Lomorage-MainActivity,fts.size = 0
1645676570787,2022.02.24 12:22:50.787,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676570787,2022.02.24 12:22:50.787,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676570789,2022.02.24 12:22:50.789,INFO,Lomorage-r,freeSpace: 11673186304, total: 115248328704
1645676570845,2022.02.24 12:22:50.845,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676570846,2022.02.24 12:22:50.846,ERROR,Lomorage-i,not login, return
1645676570847,2022.02.24 12:22:50.847,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676583338,2022.02.24 12:23:03.338,DEBUG,Lomorage-MainActivity,fts.size = 1
1645676583383,2022.02.24 12:23:03.383,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676583383,2022.02.24 12:23:03.383,DEBUG,Lomorage-g,onDetach
1645676583418,2022.02.24 12:23:03.418,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676584756,2022.02.24 12:23:04.756,DEBUG,Lomorage-MainActivity$i0,main>>life>>mOnNavigationItemSelectedListener, menu title: 照片
1645676584757,2022.02.24 12:23:04.757,DEBUG,Lomorage-MainActivity$i0,fts.size = 1
1645676584764,2022.02.24 12:23:04.764,ERROR,Lomorage-j,getSettingsFromExternalFolde: cnfFile not existed: /storage/emulated/0/Android/data/com.lomoware.lomorage/files/conf/local_dir_set.cnf
1645676585858,2022.02.24 12:23:05.858,DEBUG,Lomorage-MainActivity,fts.size = 0
1645676585929,2022.02.24 12:23:05.929,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676585929,2022.02.24 12:23:05.929,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676585931,2022.02.24 12:23:05.931,INFO,Lomorage-r,freeSpace: 11667922944, total: 115248328704
1645676585951,2022.02.24 12:23:05.951,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676585951,2022.02.24 12:23:05.951,ERROR,Lomorage-i,not login, return
1645676587410,2022.02.24 12:23:07.410,DEBUG,Lomorage-MainActivity,fts.size = 1
1645676588648,2022.02.24 12:23:08.648,DEBUG,Lomorage-MainActivity,main>>life>>onPause
1645676588925,2022.02.24 12:23:08.925,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676588929,2022.02.24 12:23:08.929,DEBUG,Lomorage-f$b,Service discovery started: _lomod._tcp.
1645676600547,2022.02.24 12:23:20.547,DEBUG,Lomorage-MainActivity,main>>life>>onResume true
1645676600571,2022.02.24 12:23:20.571,INFO,Lomorage-a,DailyView>> bind header, title = 周二: 2022年02月22日
1645676600572,2022.02.24 12:23:20.572,INFO,Lomorage-e,mItem = -2125318961, 2fe78c9fb90531067d6a70c4e5647ebb31f38221
1645676600583,2022.02.24 12:23:20.583,INFO,Lomorage-a,DailyView>> bind header, title = 周日: 2022年02月20日
1645676600584,2022.02.24 12:23:20.584,INFO,Lomorage-e,mItem = 1288628116, 14166006fb1f2ca6e3437d9c336ee338ce064ae4
1645676600588,2022.02.24 12:23:20.588,INFO,Lomorage-e,mItem = -1015628315, 367e4095fa8d6948867b999535e65d27459304ef
1645676600592,2022.02.24 12:23:20.592,INFO,Lomorage-e,mItem = -498661809, c51056bb25c2d6a644a742850259fb7911e2ffab
1645676600595,2022.02.24 12:23:20.595,INFO,Lomorage-e,mItem = -1826257779, e63d2beae4ddd0918abc8c5a9242f45c18314ac7
1645676600601,2022.02.24 12:23:20.601,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676600602,2022.02.24 12:23:20.602,INFO,Lomorage-e,mItem = 525668759, f2bd0c67ed669fb76f07e60933ad2b13f82dd5c9
1645676600606,2022.02.24 12:23:20.606,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676600607,2022.02.24 12:23:20.607,INFO,Lomorage-e,mItem = 1340409561, b67516b80e38ad3e61c287fb1411594e35b4cdad
1645676600610,2022.02.24 12:23:20.610,INFO,Lomorage-a,DailyView>> bind header, title = 周六: 2022年02月19日
1645676600612,2022.02.24 12:23:20.612,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676600612,2022.02.24 12:23:20.612,INFO,Lomorage-e,mItem = 1743999380, fa3bb82786eb10df30f68ee3bd6136a208645c3a
1645676601010,2022.02.24 12:23:21.010,INFO,Lomorage-f$b,Discovery stopped: _lomod._tcp.
1645676605757,2022.02.24 12:23:25.757,DEBUG,Lomorage-MainActivity,fts.size = 1
1645676605791,2022.02.24 12:23:25.791,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676605791,2022.02.24 12:23:25.791,DEBUG,Lomorage-g,onDetach
1645676605823,2022.02.24 12:23:25.823,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676606593,2022.02.24 12:23:26.593,DEBUG,Lomorage-MainActivity$i0,main>>life>>mOnNavigationItemSelectedListener, menu title: 照片
1645676606593,2022.02.24 12:23:26.593,DEBUG,Lomorage-MainActivity$i0,fts.size = 1
1645676606600,2022.02.24 12:23:26.600,ERROR,Lomorage-j,getSettingsFromExternalFolde: cnfFile not existed: /storage/emulated/0/Android/data/com.lomoware.lomorage/files/conf/local_dir_set.cnf
1645676607358,2022.02.24 12:23:27.358,DEBUG,Lomorage-MainActivity,fts.size = 0
1645676607433,2022.02.24 12:23:27.433,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676607434,2022.02.24 12:23:27.434,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676607437,2022.02.24 12:23:27.437,INFO,Lomorage-r,freeSpace: 11692969984, total: 115248328704
1645676607461,2022.02.24 12:23:27.461,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676607462,2022.02.24 12:23:27.462,ERROR,Lomorage-i,not login, return
1645676608362,2022.02.24 12:23:28.362,DEBUG,Lomorage-MainActivity,fts.size = 1
1645676609121,2022.02.24 12:23:29.121,DEBUG,Lomorage-MainActivity,main>>life>>onPause
1645676609152,2022.02.24 12:23:29.152,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676609154,2022.02.24 12:23:29.154,DEBUG,Lomorage-f$b,Service discovery started: _lomod._tcp.
1645676610053,2022.02.24 12:23:30.053,DEBUG,Lomorage-MainActivity,main>>life>>onResume true
1645676610074,2022.02.24 12:23:30.074,INFO,Lomorage-a,DailyView>> bind header, title = 周二: 2022年02月22日
1645676610075,2022.02.24 12:23:30.075,INFO,Lomorage-e,mItem = -2125318961, 2fe78c9fb90531067d6a70c4e5647ebb31f38221
1645676610081,2022.02.24 12:23:30.081,INFO,Lomorage-a,DailyView>> bind header, title = 周日: 2022年02月20日
1645676610082,2022.02.24 12:23:30.082,INFO,Lomorage-e,mItem = 1288628116, 14166006fb1f2ca6e3437d9c336ee338ce064ae4
1645676610086,2022.02.24 12:23:30.086,INFO,Lomorage-e,mItem = -1015628315, 367e4095fa8d6948867b999535e65d27459304ef
1645676610090,2022.02.24 12:23:30.090,INFO,Lomorage-e,mItem = -498661809, c51056bb25c2d6a644a742850259fb7911e2ffab
1645676610094,2022.02.24 12:23:30.094,INFO,Lomorage-e,mItem = -1826257779, e63d2beae4ddd0918abc8c5a9242f45c18314ac7
1645676610105,2022.02.24 12:23:30.105,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676610106,2022.02.24 12:23:30.106,INFO,Lomorage-e,mItem = 525668759, f2bd0c67ed669fb76f07e60933ad2b13f82dd5c9
1645676610111,2022.02.24 12:23:30.111,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676610111,2022.02.24 12:23:30.111,INFO,Lomorage-e,mItem = 1340409561, b67516b80e38ad3e61c287fb1411594e35b4cdad
1645676610117,2022.02.24 12:23:30.117,INFO,Lomorage-a,DailyView>> bind header, title = 周六: 2022年02月19日
1645676610120,2022.02.24 12:23:30.120,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676610120,2022.02.24 12:23:30.120,INFO,Lomorage-e,mItem = 1743999380, fa3bb82786eb10df30f68ee3bd6136a208645c3a
1645676610525,2022.02.24 12:23:30.525,INFO,Lomorage-f$b,Discovery stopped: _lomod._tcp.
1645676611451,2022.02.24 12:23:31.451,DEBUG,Lomorage-MainActivity,fts.size = 1
1645676612972,2022.02.24 12:23:32.972,DEBUG,Lomorage-MainActivity,main>>life>>onPause
1645676613001,2022.02.24 12:23:33.001,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676613004,2022.02.24 12:23:33.004,DEBUG,Lomorage-f$b,Service discovery started: _lomod._tcp.
1645676650767,2022.02.24 12:24:10.767,INFO,Lomorage-LoginActivity,getBaseUrlFromUI, baseUrl = http://10.133.228.155:8000, isRemoteMode = false
1645676650813,2022.02.24 12:24:10.813,DEBUG,Lomorage-t,lomod service is health 200
1645676660828,2022.02.24 12:24:20.828,ERROR,Lomorage-e,getMountDiskSpaceEx Exception timeout
1645676660830,2022.02.24 12:24:20.830,ERROR,Lomorage-LoginActivity$e,Lomod DIR = 0  !!!
1645676666570,2022.02.24 12:24:26.570,DEBUG,Lomorage-MainActivity,main>>life>>onResume true
1645676666591,2022.02.24 12:24:26.591,INFO,Lomorage-a,DailyView>> bind header, title = 周二: 2022年02月22日
1645676666592,2022.02.24 12:24:26.592,INFO,Lomorage-e,mItem = -2125318961, 2fe78c9fb90531067d6a70c4e5647ebb31f38221
1645676666608,2022.02.24 12:24:26.608,INFO,Lomorage-a,DailyView>> bind header, title = 周日: 2022年02月20日
1645676666608,2022.02.24 12:24:26.608,INFO,Lomorage-e,mItem = 1288628116, 14166006fb1f2ca6e3437d9c336ee338ce064ae4
1645676666615,2022.02.24 12:24:26.615,INFO,Lomorage-e,mItem = -1015628315, 367e4095fa8d6948867b999535e65d27459304ef
1645676666624,2022.02.24 12:24:26.624,INFO,Lomorage-e,mItem = -498661809, c51056bb25c2d6a644a742850259fb7911e2ffab
1645676666629,2022.02.24 12:24:26.629,INFO,Lomorage-e,mItem = -1826257779, e63d2beae4ddd0918abc8c5a9242f45c18314ac7
1645676666639,2022.02.24 12:24:26.639,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676666639,2022.02.24 12:24:26.639,INFO,Lomorage-e,mItem = 525668759, f2bd0c67ed669fb76f07e60933ad2b13f82dd5c9
1645676666647,2022.02.24 12:24:26.647,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676666647,2022.02.24 12:24:26.647,INFO,Lomorage-e,mItem = 1340409561, b67516b80e38ad3e61c287fb1411594e35b4cdad
1645676666654,2022.02.24 12:24:26.654,INFO,Lomorage-a,DailyView>> bind header, title = 周六: 2022年02月19日
1645676666656,2022.02.24 12:24:26.656,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null
1645676666656,2022.02.24 12:24:26.656,INFO,Lomorage-e,mItem = 1743999380, fa3bb82786eb10df30f68ee3bd6136a208645c3a
1645676667082,2022.02.24 12:24:27.082,INFO,Lomorage-f$b,Discovery stopped: _lomod._tcp.
1645676724262,2022.02.24 12:25:24.262,INFO,Lomorage-g$e,App version: V0.92-12272021
1645676724262,2022.02.24 12:25:24.262,INFO,Lomorage-g$e,App version code: 35
1645676724268,2022.02.24 12:25:24.268,ERROR,Lomorage-l,getLoggedInUserInfo>> encryptedData = null

**Comment by aisnote** [comment]
客户端 取不到 服务器端的 盘符目录

> 1645676660828,2022.02.24 12:24:20.828,ERROR,Lomorage-e,**getMountDiskSpaceEx Exception timeout**
1645676660830,2022.02.24 12:24:20.830,ERROR,Lomorage-LoginActivity$e,Lomod DIR = 0 !!!

看看 docker 内的 /media  目录是什么样的？ ls 一下 贴上来

**Comment by zgc999** [comment]
root@4a9dd760ac23:/media# ls
backup  primary
就两个目录

**Comment by aisnote** [comment]
@dwebfan  could you give some comments?

**Comment by leslie-wang** [comment]
@zgc999 What is the version of your docker image? The latest image was pushed 7 days ago.

**Comment by zgc999** [comment]
重新拉取容器，可以了创建账号了。
