### ISSUE TITLE
docker 的登录账号是什么

### ISSUE THREAD

**Issue by bob-token** [lomorage/lomo-docker#12]
lomorage/raspberrypi-lomorage:latest
是在树莓派上运行的
我试了一些账号不能进入：
pi，raspberry
lomoware,lomorage

**Comment by bob-token** [comment]
lomorage/raspberrypi-lomorage:latest

**Comment by bob-token** [comment]
是在树莓派上运行的
我试了一些账号不能进入

**Comment by leslie-wang** [comment]
您是说网页的登陆账号么？如果是的话，请用手机app先生成用户。

**Comment by bob-token** [comment]
手机创建用户失败，日志如下：
time="2022-03-02T05:35:01Z" level=warning msg="read /dev/root uuid from /dev/disk/by-uuid/: Resource not found"
time="2022-03-02T05:35:01Z" level=warning msg="read /dev/root uuid via blkid: blkid -o export -p --uuid -i /dev/root:  blkid: error: /dev/root: No such file or directory\n: exit status 2"
time="2022-03-02T05:35:01Z" level=warning msg="Unable to find uuid for /media/backup"
time="2022-03-02T05:35:01Z" level=info msg="process mount: 318 299 179:2 /data/media/primary /media/primary rw,relatime - ext4 /dev/root rw,errors=remount-ro"
time="2022-03-02T05:35:01Z" level=warning msg="read /dev/root uuid via lsblk: lsblk -o UUID -P /dev/root:  lsblk: /dev/root: not a block device\n: exit status 32"
time="2022-03-02T05:35:01Z" level=info msg="probe uuid directory: /dev/disk/by-uuid/"
time="2022-03-02T05:35:01Z" level=info msg="/dev/disk/by-uuid/2887d26c-6ae7-449d-9701-c5a4018755b0 -> ../../mmcblk0p2\n"
time="2022-03-02T05:35:01Z" level=info msg="/dev/disk/by-uuid/4AD7-B4D5 -> ../../mmcblk0p1\n"
time="2022-03-02T05:35:01Z" level=warning msg="read /dev/root uuid from /dev/disk/by-uuid/: Resource not found"
time="2022-03-02T05:35:01Z" level=warning msg="read /dev/root uuid via blkid: blkid -o export -p --uuid -i /dev/root:  blkid: error: /dev/root: No such file or directory\n: exit status 2"
time="2022-03-02T05:35:01Z" level=warning msg="Unable to find uuid for /media/primary"
time="2022-03-02T05:35:01Z" level=info msg="found mount dirs: map[/media:0x3f78360]"
time="2022-03-02T05:35:01Z" level=error msg="http reply: Invalid Disk Mount"

**Comment by fuji246** [comment]
Do you have disk mounted?  You can try disable disk mount monitor is having some problem when monitoring the disk status

```
LOMOD_DISABLE_MOUNT_MONITOR=1
```

**Comment by fuji246** [comment]
@bob-token , 参考README里面，加上`LOMOD_DISABLE_MOUNT_MONITOR=1`试试吧。

**Comment by fuji246** [comment]
LOMOD_DISABLE_MOUNT_MONITOR by default now.

**Comment by bob-token** [comment]
收到，谢谢！
