### ISSUE TITLE
运行一段时间后 提示 Device is not mounted yet 无法在web中预览图

### ISSUE THREAD

**Issue by yybinpitaya** [lomorage/lomo-docker#13]
Unraid Docker 中运行一段时间后
发现在web中无法看预览图
日志报错
Device is not mounted yet

映射对应路径看了是有图片文件的

开始是对的

**Comment by fuji246** [comment]
可以试试参考README，把`LOMOD_DISABLE_MOUNT_MONITOR=1`加上试试。

**Comment by fuji246** [comment]
@yybinpitaya , 上面的方法可以吗?

**Comment by yybinpitaya** [comment]
可以了
