### ISSUE TITLE
能支持一下termux吗

### ISSUE THREAD

**Issue by kevencoff1116** [lomorage/lomo-docker#17]

**Comment by fuji246** [comment]
能具体点吗？比如使用场景是什么？没有用过termux，你是要在Android设备上运行服务程序吗？

**Comment by kevencoff1116** [comment]
对的，想在安卓上开服务，然后如果使用docker，好像需要重新编译内核，比较复杂，有没有比较简单的方法？

**Comment by aisnote** [comment]
有什么原因要用android做服务器呢？
