### ISSUE TITLE
手动删除服务器端照片后，app里仍然显示照片已备份

### ISSUE THREAD

**Issue by WayeeWang** [lomorage/lomo-docker#19]
新年快乐！

Use case:
我的手机里有很多照片，通过lomorage备份到RPi硬盘里。然后我自己写了一个电子相框的app读取和展示这些照片。
有不少图片很相似，或者需要删除。所以我的电子相框app可以从lomorage的备份文件夹中把不需要的照片文件删掉。
但是删除服务器端的照片后，lomorage的app里仍然显示删掉的照片已备份，而不是“仅本地”。

**Comment by fuji246** [comment]
只删除文件是有问题的，数据库也要清理，你最好是通过app去删除，手机app，或者你可以看web app调用的api
