### ISSUE TITLE
Image platform (linux/amd64) does not match the detected host platform (linux/arm64/v8)

### ISSUE THREAD

**Issue by theLord-81** [lomorage/lomo-docker#2]
I am trying to install lomorage on my raspberry pi4 (8GB) using docker but the run.sh script after having downloaded the correct image from the repository is looking the wrong architecture.

Executing the script with the debug option enabled:
.....
Unable to find image 'lomorage/raspberrypi-lomorage:latest' locally
latest: Pulling from lomorage/raspberrypi-lomorage
50fb00520869: Pull complete
880064e3cd0e: Pull complete
2a823b2e172d: Pull complete
1ffcd80ca659: Pull complete
ebf5c6b64805: Pull complete
2bc938939752: Pull complete
d4e9c548781d: Pull complete
e605c1ca267c: Pull complete
d1e68a741148: Pull complete
fa6e1acf3bcb: Pull complete
9ed06594af74: Pull complete
23194d1a9f43: Pull complete
6b5605fb5f19: Pull complete
01161c01b664: Pull complete
aab97fafdd3a: Pull complete
ea8bf66a8c76: Pull complete
2bdb8bcf8a21: Pull complete
dca659a2ccce: Pull complete
13445d51b2a1: Pull complete
4a1c829744f4: Pull complete
2dedb0bdb020: Pull complete
ed0c813da318: Pull complete
087a4559789a: Pull complete
6a44b35f1791: Pull complete
08f97433f793: Pull complete
362e317ec57a: Pull complete
cb6ac5b607cb: Pull complete
dde6f60c9531: Pull complete
51495d3e047f: Pull complete
e54e110a9695: Pull complete
Digest: sha256:0b372de0329cc9cc17cccf7fa26f698f429154c64924b12dd2de6eaeceec5a94
Status: Downloaded newer image for lomorage/raspberrypi-lomorage:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
+ '[' 1 -lt 1 ']'
+ cron
+ /opt/lomorage/bin/lomod -b /lomo --max-upload 1 --max-fetch-preview 3
+ /opt/lomorage/bin/lomo-web --port 8001 --baseurl http://192.168.1.99:8000
cron: can't open or create /var/run/crond.pid: Permission denied
2021/04/06 14:25:27 Lomorage Service lomod url: http://192.168.1.99:8000
2021/04/06 14:25:27 Server started. Press Ctrl-C to stop server
time="2021-04-06T14:25:27Z" level=info msg="using file permision: -rw-r--r--, folder permission: -rwxr-x---\n"
time="2021-04-06T14:25:27Z" level=fatal msg="mkdir /lomo/etc: permission denied"

How can I fix this issue?

**Comment by fuji246** [comment]
that is a warning and should not matter, see https://github.com/balena-io-library/base-images/issues/672. However looks like ipvlan and macvlan may have some problem, will take a look.

**Comment by fuji246** [comment]
@theLord-81 , looks like the the user doesn't have access to "/lomo", see `mkdir /lomo/etc: permission denied"`. What is the command line params you use? The arch warning message doesn't matter.
