### ISSUE TITLE
支持服务器安装吗？

### ISSUE THREAD

**Issue by wrhsd1** [lomorage/lomo-docker#5]
我尝试在独立服务器上使用docker安装，可以运行，但是app无法连接服务器，网页端需要用户名和密码，也无法登录，感谢开发

**Comment by fuji246** [comment]
可以把运行命令发一下看看，另外可以看看lomohome(设置的lomohome目录参数)目录下的lomod.log，或者把"lomohome/var/log/"打包发到support@lomorage.com吧。

**Comment by wrhsd1** [comment]
> 可以把运行命令发一下看看，另外可以看看lomohome(设置的lomohome目录参数)目录下的lomod.log，或者把"lomohome/var/log/"打包发到[support@lomorage.com](mailto:support@lomorage.com)吧。

我试了试 成功了 用服务器的ip登录进去了 感谢回复
