### ISSUE TITLE
Ubuntu docker报错

### ISSUE THREAD

**Issue by zhang24xiao** [lomorage/lomo-docker#6]
在docker环境下运行发现报这个错误：
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "127.0.0.1": executable file not found in $PATH: unknown.

麻烦开发人员确认一下，感谢！

**Comment by zhang24xiao** [comment]
docker完整的执行命令：
sudo docker run --user=1000:1000 -d --privileged --cap-add=ALL -p 8000:8000 -p 8001:8001 -v "/home/zhangjinze/图片:/media" -v "/home/zhangjinze/文档:/lomo" -v /dev:/dev --rm --name=lomorage "lomorage/amd64-lomorage:latest" 127.0.0.1 8000 8001

**Comment by fuji246** [comment]
更新下docker image试试吧
