### ISSUE TITLE
关于部署问题

### ISSUE THREAD

**Issue by zsfjim** [lomorage/lomo-docker#7]
这个说明真是太敷衍了，真的有人能看懂这个部署方式？是不打算让人用docker版的吧。。。

**Comment by fuji246** [comment]
@zsfjim 是什么平台？有些用户提过需要有一些特定平台，比如群晖，unraid下docker的安装，大致看了那些可能很多都是GUI的操作界面，还没来得及整理，是打算做的。现在这里的提供的都是命令行的。我们一个个的来吧，这个命令行的也整理下。

**Comment by zsfjim** [comment]
其实unraid和群晖配置基本都是通用的，随便出一个，大家应该都看得懂。。。。或者举例一个完整的docker命令也能看得懂👍

**Comment by xiaodhu** [comment]
这是我在unraid里面配置lomorage docker的步骤，供参考。

- 登录到unraid的UI中，Click **DOCKER**，然后click **add container**，会进入到add container的配置页面，先click右上角的**basic view**按钮，切换到advanced view


- 下面是我的配置：

```
Name: Lomorage
Repository: lomorage/amd64-lomorage
Categories: Backup: MediaApp:Video MediaApp:Photos MediaServer:Video MediaServer:Photos Status:Stable
Project Page: https://github.com/lomorage/lomo-docker
Docker Hub URL: https://hub.docker.com/r/lomorage/amd64-lomorage
Extra Parameters: --user=99:100
Post Arguments: 192.168.1.28 8000 8001 （这里需要用你自己的unraid IP来替换192.168.1.28）
Network Type: Host
Console shell command: Shell
Privileged: OFF
```
然后click最下面**Add another Path, Port, Variable, Label or Device**，增加三个path
第一个配置：
```
Config Type: Path
Name: MediaDir
Container Path: /media
Host Path: /mnt/user/
```
其他不变，click SAVE保存
Click Add，增加 第二个path：
```
Config Type: Path
Name: AppDir
Container Path: /lomo
Host Path: /mnt/user/appdata/
```
增加第三个path
```
Config Type: Path
Name: User
Container Path: /etc/passwd
Host Path: /etc/passwd
```
添加之后，click **APPLY**

- apply之后会在**DOCKER** tab里面，application出现lomorage的app，点击lomorage的图标，在出现的list里面选择start，几秒钟后，如果没有配置错误，会看到运行的绿色三角形started图标，如果有错误的，会出现红色方块的stop图标，你可以再次点击，查看log

这是完整的cmd
`/usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker create --name='Lomorage' --net='host' -e TZ="America/Los_Angeles" -e HOST_OS="Unraid" -v '/mnt/user/':'/media':'rw' -v '/mnt/user/appdata/':'/lomo':'rw' -v '/etc/passwd':'/etc/passwd':'rw' --user=99:100 'lomorage/amd64-lomorage' 192.168.1.28 8000 8001`

**Comment by zsfjim** [comment]
很详细，非常感谢！

**Comment by fuji246** [comment]
https://docs.lomorage.com/docs/Installation/lomorage-service/installation-unraid/

**Comment by AKALI322** [comment]
truenas scale上的部署有无大哥教教呢，提前谢谢

**Comment by AKALI322** [comment]
truenas scale上的部署有无大哥教教呢，提前谢谢

**Comment by fuji246** [comment]
试试用docker-compose吧，
https://www.truenas.com/community/threads/truecharts-integrates-docker-compose-with-truenas-scale.99848/?utm_content=201309040&utm_medium=social&utm_source=facebook&hss_channel=fbp-207351519295239
