### ISSUE TITLE
Raspberry Pi server image is not updating automatically

### ISSUE THREAD

**Issue by CSStudySession** [lomorage/lomo-docker#8]
My Raspberry Pi server is in connection with Internet but it's not updating automatically. On the mobile client, it notes that there's newer version of server and I may need to update it.
![server_0](https://user-images.githubusercontent.com/39076805/138571674-cc308156-7ead-4220-8a1d-1eeb553e2192.jpg)
![server_0](https://user-images.githubusercontent.com/39076805/138571684-dc6a2e6e-6b99-4efd-886a-d14e94818e05.png)

**Comment by fuji246** [comment]
It's os configure issue, not docker image problem.
